import React, { useState, useEffect, useMemo } from 'react';
import { useStore } from '../context/StoreContext';
import { AffiliateStats, User } from '../types';
import { TrendingUp, Users, Lock, CheckCircle, Target, Award, Crown, ArrowRight, AlertCircle, Copy, Trophy, RefreshCw, FileText, Check, X, BookOpen, Clock, Mail, LogIn, DollarSign, Star, BarChart, Share2, ChevronRight, Network, Link as LinkIcon } from 'lucide-react';
import { Link } from 'react-router-dom';
import CurrencySelectionModal from '../components/CurrencySelectionModal';

const AffiliateProgram: React.FC = () => {
  const { user, affiliateLeaderboard, applyForAffiliate, buyAffiliateContent, joinAffiliateElite, register, login, getAllUsers, currency } = useStore();
  const [showApplyForm, setShowApplyForm] = useState(false);
  const [step, setStep] = useState(1); 
  const [showTermsModal, setShowTermsModal] = useState(false);
  
  // Pending Modal State
  const [showPendingModal, setShowPendingModal] = useState(false);

  // Application Form State
  const [formData, setFormData] = useState({
      name: user && user.name && user.name !== 'Guest' ? user.name.split(' ')[0] : '',
      surname: user && user.name && user.name !== 'Guest' ? user.name.split(' ').slice(1).join(' ') : '',
      email: user?.email || '',
      dob: user?.birthday || '',
      gender: '',
      reason: '',
      socials: '',
      password: '' 
  });
  
  const [acceptTerms, setAcceptTerms] = useState(false);
  const [acknowledgeReality, setAcknowledgeReality] = useState(false); 
  const [applicationSubmitted, setApplicationSubmitted] = useState(false);

  // Inline Login State
  const [loginMode, setLoginMode] = useState(false);
  const [loginPassword, setLoginPassword] = useState('');
  const [loginError, setLoginError] = useState('');

  // Terms State
  const [sectionAgreements, setSectionAgreements] = useState<Record<number, boolean>>({});

  // Dashboard State
  const [copiedLink, setCopiedLink] = useState(false);
  
  // Recruits State
  const [myRecruits, setMyRecruits] = useState<User[]>([]);

  // Currency Modal State
  const [showCurrencyModal, setShowCurrencyModal] = useState(false);

  // Check Status & Load Recruits
  useEffect(() => {
      if (user.affiliateStats?.status === 'pending') {
          setShowPendingModal(true);
      }
      
      if (user.affiliateStats?.status === 'approved') {
          getAllUsers().then(users => {
              const recruits = users.filter(u => u.affiliateStats?.parentId === user.id);
              setMyRecruits(recruits);
          });
      }

      // Show currency modal if not locked
      if (user.affiliateStats?.status === 'approved' && !user.currencyLocked) {
          setShowCurrencyModal(true);
      }
  }, [user.affiliateStats, user.id, user.currencyLocked, getAllUsers]);

  const termsSections = useMemo(() => [
    {
        title: "1. Introduction",
        content: `These Terms and Conditions ("Agreement") govern your participation in the Spoil Me Vintage Partnership Program ("Program"). By enrolling in the Program, you agree to be bound by these terms.`
    },
    {
        title: "2. Definitions",
        content: `"Partner", "You", and "Your" refer to the individual or entity applying for or participating in the Program. "We", "Us", and "Our" refer to Spoil Me Vintage. "Commission" refers to the amount paid for a successful referral. "Net Sales" refers to the final sale price of a product EXCLUDING shipping costs, customs duties, taxes (VAT), and any refunds.`
    },
    {
        title: "3. Enrollment",
        content: `To begin the enrollment process, you must submit a complete Partnership Application. We will evaluate your application and notify you of your acceptance or rejection. We reserve the right to reject applications from sites or profiles that do not meet our brand standards.`
    },
    {
        title: "4. Affiliate Links",
        content: `You will be issued a unique Affiliate URL or code. Sales must be tracked via these links to generate commission. We use a 30-day cookie window. It is your responsibility to ensure that these links are correctly formatted and used on your site.`
    },
    {
        title: "5. Commissions & Earnings",
        content: `You will earn commissions based on the specific product category sold: 5.1. Standard Jewelry: Earn 10% to 20% on Net Sales based on your monthly performance tier. 5.2. "Secret Vault" Items: Due to the clearance pricing of Vault items, these sales earn a flat 1% Commission regardless of your tier. 5.3. Memberships: Earn a fixed monthly recurring commission (ZAR R2-R15 or USD $1-$3) for active, paid subscriptions. 5.4. Override: Earn a 1% bonus on Net Sales generated by partners you directly recruit.`
    },
    {
        title: "6. Payment Terms & Currency",
        content: `Commissions are paid once a month. 6.1. South African Partners: Paid via EFT to a valid SA Bank Account. International earnings (USD) are converted to ZAR at the bank rate. Minimum payout: R200. 6.2. International Partners: Paid via PayPal in USD. South African earnings (ZAR) are converted to USD at the bank rate. Minimum payout: $50.`
    },
    {
        title: "7. \"Secret Vault\" Items",
        content: `This section strictly governs the purchase of discounted items from the "Secret Vault." 7.1. Nature of Goods ("Sold As-Is"): Items listed in "The Secret Vault" (priced from R10 / $1) may include: Factory overstock, Sample items, Items with minor cosmetic imperfections ("Rejects" or "Seconds"). ALL SALES FROM THE SECRET VAULT ARE FINAL. NO RETURNS, REFUNDS, OR EXCHANGES ARE PERMITTED ON THESE ITEMS. 7.2. The "Loyalty Ladder" & Purchase Limits: To prevent resale abuse, purchase limits apply to The Secret Vault based on consecutive months of membership: Month 1: Maximum 5 items, Month 2: Maximum 7 items, Month 3: Maximum 10 items, Month 4+: Unlimited. 7.3. The "Reset Rule" (Strict Enforcement): Membership continuity is required to maintain your "Loyalty Ladder" status. If you cancel your subscription or if your payment fails and is not rectified within 48 hours, your Loyalty Ladder status RESETS TO MONTH 1.`
    },
    {
        title: "8. Competitions & Weekly Drops",
        content: `8.1. Promotional Competition: The "Spoil Me" package (R19) includes entry into giveaways. This is a promotional competition under the South African Consumer Protection Act (CPA), not a lottery. You are paying for the Membership Services (Sales alerts, Vouchers), and the entry is a complimentary benefit. 8.2. International Winners: If a winner is selected from outside South Africa: Physical prizes may be converted to Store Credit of equivalent value to avoid shipping fees. If the winner requests the physical item, the winner is responsible for all international shipping costs and customs duties.`
    },
    {
        title: "9. International Orders & Shipping",
        content: `9.1. Customs, Duties, and Taxes: DDU (Delivered Duty Unpaid): For all international orders (outside South Africa), Spoil Me Vintage is NOT responsible for any customs fees, import duties, or local taxes. These fees are the sole responsibility of the customer. If you refuse to pay customs fees and the package is returned to us, we will deduct the return shipping costs from any potential refund. 9.2. Shipping Times: International shipping times are estimates (typically 10-25 business days). We are not liable for delays caused by customs departments or global logistics strikes.`
    },
    {
        title: "10. Returns and Refunds",
        content: `10.1. Standard Products (Non-Vault): South Africa: You may return unused, undamaged standard jewelry within 7 days of receipt for a store credit or exchange, in accordance with the CPA. International: Due to high shipping costs, international returns are generally not accepted unless the item arrived damaged. Evidence (photos) must be provided within 24 hours of delivery. 10.2. Non-Returnable Items: The following items are final sale and cannot be returned: Earrings (for hygiene reasons), Secret Vault Items, Customized or personalized jewelry.`
    },
    {
        title: "11. Limitation of Liability",
        content: `To the fullest extent permitted by law, Spoil Me Vintage shall not be liable for: Allergic Reactions: Our jewelry materials are listed on the product page. It is the customer's responsibility to verify they are not allergic to metals (e.g., nickel, copper, alloys) before wearing. We are not liable for skin reactions. Indirect Damages: Any indirect, incidental, or consequential damages arising from the use of our products or website. Maximum Liability: In no event shall our total liability to you exceed the amount you paid to us in the 3 months preceding the claim.`
    },
    {
        title: "12. Payment Terms",
        content: `Payments are processed securely via third-party providers (e.g., PayFast, Stripe, Yoco). Spoil Me Vintage does not store your full credit card details. By subscribing, you authorize us to charge your payment method automatically every month until you cancel.`
    },
    {
        title: "13. Governing Law and Dispute Resolution",
        content: `These Terms are governed by the laws of the Republic of South Africa. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the Magistrate's Court in Worcester, Western Cape. For International customers, you agree to waive any right to class action lawsuits and agree to resolve disputes through binding arbitration in South Africa, or via amicable email resolution.`
    },
    {
        title: "14. Commission Rates & Exceptions",
        content: `14.1. Standard Products: Commission rates (10% - 20%) apply to all full-priced, standard retail jewelry items based on your monthly performance tier. 14.2. "Secret Vault" Items: Items purchased from "The Secret Vault" (Clearance/Sample stock) are sold at near-cost prices. Therefore, all Vault items earn a flat 1% commission, regardless of your current Tier status. 14.3. Shipping & Taxes: Commissions are calculated on the Net Product Price only. Shipping fees, taxes, and duties are excluded from all calculations. 14.4. Payouts: South Africa: Paid via EFT (ZAR). International earnings converted to ZAR. International: Paid via PayPal (USD). South African earnings converted to USD.`
    },
    {
        title: "15. CONTACT US",
        content: `For questions regarding these Terms, please contact us at: Email: spoilmevintagediy@gmail.com WhatsApp: +27 71858 9370`
    }
  ], []);

  const allTermsChecked = termsSections.length > 0 && termsSections.every((_, index) => sectionAgreements[index]);

  // ... [Login and Apply Handlers same as before] ...
  const handleInlineLogin = async (e: React.FormEvent) => {
      e.preventDefault();
      setLoginError('');
      const success = await login(formData.email, loginPassword);
      
      if (success) {
          setLoginMode(false);
          setStep(2); 
          const allUsers = await getAllUsers();
          const thisUser = allUsers.find(u => u.email.toLowerCase() === formData.email.toLowerCase());
          if (thisUser?.affiliateStats?.status === 'approved') {
              setShowApplyForm(false);
              setTimeout(() => document.getElementById('affiliate-dashboard')?.scrollIntoView({ behavior: 'smooth' }), 500);
          }
      } else {
          setLoginError('Invalid password. Please try again.');
      }
  };

  const handleApply = async (e: React.FormEvent) => {
      e.preventDefault();
      if (!formData.reason.trim() || !acceptTerms) return;
      
      const notification: any = {
          id: `aff_sub_${Date.now()}`,
          type: 'system',
          title: 'Partnership Application Received',
          message: 'Your application to become a partner is pending review. Good luck!',
          date: new Date().toISOString(),
          isRead: false
      };

      const affiliateStatsData: AffiliateStats = {
          status: 'pending',
          gender: formData.gender as any,
          joinReason: `${formData.reason} | Socials: ${formData.socials}`,
          totalSalesCount: 0,
          totalSalesValue: 0,
          commissionRate: 10,
          balance: 0,
          recurringBalance: 0,
          isElite: false,
          hasContentAccess: false
      };

      if (!user.email) {
          if (!formData.email || !formData.password) {
              alert("Please provide email and password to create your account.");
              return;
          }
          const allUsers = await getAllUsers();
          const existingUser = allUsers.find(u => u.email.toLowerCase() === formData.email.toLowerCase());
          
          if (existingUser) {
              setLoginMode(true);
              setLoginError("This email address is already associated with an account. Please Log In to continue your application.");
              return;
          }
          
          const success = await register({
              name: `${formData.name} ${formData.surname}`,
              email: formData.email,
              password: formData.password,
              birthday: formData.dob,
              notifications: [notification],
              affiliateStats: affiliateStatsData
          });
          
          if (!success) {
              alert("Failed to create account. Please try again.");
              return;
          }
          setApplicationSubmitted(true);
      } else {
          await applyForAffiliate(formData);
          setApplicationSubmitted(true);
      }
  };

  const closeAndReset = () => {
      setShowApplyForm(false);
      setApplicationSubmitted(false);
      setStep(1);
      setAcknowledgeReality(false);
      setAcceptTerms(false);
      setSectionAgreements({});
      setLoginMode(false);
      setLoginPassword('');
      setLoginError('');
  }

  const handleBuyContent = async () => {
      if (window.confirm("Purchase the Partner Content Pack for R250?")) {
          await buyAffiliateContent();
          alert("Content Unlocked!");
      }
  };

  const handleJoinElite = async () => {
      if (window.confirm("Upgrade to Elite Partner Status? A fee applies.")) {
          await joinAffiliateElite();
          alert("Welcome to the Elite Squad!");
      }
  };

  const handleConfirmTerms = () => {
      setAcceptTerms(true);
      setShowTermsModal(false);
  };

  const toggleSectionAgreement = (index: number) => {
      setSectionAgreements(prev => ({
          ...prev,
          [index]: !prev[index]
      }));
  };

  const copyLink = () => {
      const link = `${window.location.origin}/#/?ref=${user.affiliateCode}`;
      navigator.clipboard.writeText(link);
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2000);
  };

  const stats = user.affiliateStats || {
      status: 'none',
      totalSalesCount: 0,
      totalSalesValue: 0,
      commissionRate: 10,
      balance: 0,
      recurringBalance: 0,
      isElite: false,
      hasContentAccess: false
  };

  const isAffiliate = stats.status === 'approved';

  // COMMISSION TIERS BASED ON ALL-TIME SALES VALUE
  const tiers = [
    { name: 'Bronze', rate: 10, min: currency === 'ZAR' ? 0 : 0, max: currency === 'ZAR' ? 2000 : 200 },
    { name: 'Silver', rate: 11, min: currency === 'ZAR' ? 2001 : 201, max: currency === 'ZAR' ? 5000 : 500 },
    { name: 'Gold', rate: 15, min: currency === 'ZAR' ? 5001 : 501, max: currency === 'ZAR' ? 10000 : 1000 },
    { name: 'Platinum', rate: 20, min: currency === 'ZAR' ? 10001 : 1001, max: currency === 'ZAR' ? 25000 : 2500 }
  ];

  // FIND CURRENT TIER
  const currentTier = tiers.find(tier => stats.totalSalesValue >= tier.min && stats.totalSalesValue <= tier.max) || tiers[0];
  const currentTierIndex = tiers.indexOf(currentTier);

  // PROGRESS TO NEXT TIER
  let nextTier = null;
  let progressPercent = 100;
  if (currentTierIndex < tiers.length - 1) {
    nextTier = tiers[currentTierIndex + 1];
    const range = nextTier.min - currentTier.min;
    const progress = stats.totalSalesValue - currentTier.min;
    progressPercent = (progress / range) * 100;
  }

  return (
    <div className="max-w-6xl mx-auto py-8 space-y-16">
        <style>{`
            @keyframes marquee {
                0% { transform: translateX(100%); }
                100% { transform: translateX(-100%); }
            }
            .animate-marquee {
                animation: marquee 20s linear infinite;
            }
        `}</style>

        {/* HERO */}
        <div className="relative rounded-3xl overflow-hidden bg-zinc-900 border border-pink-500/30 min-h-[400px] flex items-center">
            <div className="absolute inset-0 bg-gradient-to-r from-black via-zinc-900/90 to-transparent z-10"></div>
            <div className="absolute right-0 top-0 h-full w-1/2 bg-[url('https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80')] bg-cover bg-center opacity-40 grayscale mix-blend-luminosity"></div>
            
            <div className="relative z-20 p-8 md:p-16 max-w-2xl space-y-6">
                <div className="inline-flex items-center gap-2 bg-pink-900/30 border border-pink-500/50 text-pink-400 px-4 py-1.5 rounded-full text-sm font-bold uppercase tracking-wider">
                    <Target size={16} /> Join the Team
                </div>
                <h1 className="font-cherry text-5xl md:text-7xl text-white leading-none drop-shadow-[0_0_15px_rgba(236,72,153,0.6)]">
                    {currency === 'ZAR' ? 'Turn Passion into Profit' : 'Turn Passion into Profit'}
                </h1>
                <p className="text-gray-300 text-lg leading-relaxed">
                    {currency === 'ZAR'
                        ? 'Join the Spoil Me Team. Earn up to 20% Commission + Monthly Recurring Rands.'
                        : 'Join the Spoil Me Team. Earn up to 20% Commission + Monthly Recurring Cash.'
                    }
                </p>
                
                {!isAffiliate && stats.status !== 'pending' && (
                    <button 
                        onClick={() => setShowApplyForm(true)}
                        className="px-8 py-4 bg-white text-black font-bold rounded-full hover:bg-gray-200 transition-all shadow-[0_0_20px_rgba(255,255,255,0.4)] flex items-center gap-2"
                    >
                        {currency === 'ZAR' ? 'JOIN THE TEAM (ZA)' : 'JOIN THE TEAM (GLOBAL)'} <ArrowRight size={20} />
                    </button>
                )}
                {stats.status === 'pending' && (
                    <button 
                        onClick={() => setShowPendingModal(true)}
                        className="inline-flex items-center gap-2 bg-yellow-900/20 border border-yellow-500/30 text-yellow-400 px-6 py-3 rounded-lg font-bold hover:bg-yellow-900/40 transition-colors"
                    >
                        <Clock size={18} /> Check Application Status
                    </button>
                )}
                {isAffiliate && (
                    <button 
                        onClick={() => document.getElementById('affiliate-dashboard')?.scrollIntoView({ behavior: 'smooth' })}
                        className="px-8 py-4 bg-green-600 text-white font-bold rounded-full hover:bg-green-500 transition-all shadow-[0_0_20px_rgba(34,197,94,0.4)] flex items-center gap-2"
                    >
                        Go to Dashboard <ArrowRight size={20} />
                    </button>
                )}
            </div>
        </div>

        {/* SOCIAL PROOF TICKER */}
        <div className={`overflow-hidden bg-zinc-900/50 border border-gray-800 rounded-2xl p-4 ${currency === 'ZAR' ? 'view-zar' : 'view-usd'}`}>
            <div className="flex items-center gap-2 mb-2">
                <Trophy className="text-yellow-500" size={20} />
                <span className="text-sm font-bold text-white">Recent Partner Success</span>
            </div>
            <div className="overflow-hidden">
                <div className="animate-marquee whitespace-nowrap">
                    {currency === 'ZAR' ? (
                        <>
                            <span className="inline-block mx-4 text-gray-300">💸 Sarah J. (Pretoria) earned R450...</span>
                            <span className="inline-block mx-4 text-gray-300">🚀 Thandi M. (JHB) hit Gold Tier...</span>
                            <span className="inline-block mx-4 text-gray-300">💸 Lerato K. (Durban) earned R2,000...</span>
                        </>
                    ) : (
                        <>
                            <span className="inline-block mx-4 text-gray-300">💸 Emily R. (Texas) earned $50...</span>
                            <span className="inline-block mx-4 text-gray-300">🚀 Mike T. (London) hit Gold Tier...</span>
                            <span className="inline-block mx-4 text-gray-300">💸 Jessica L. (NY) earned $120...</span>
                        </>
                    )}
                </div>
            </div>
        </div>

        {/* HOW IT WORKS & TIERS */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="bg-zinc-900/50 p-6 rounded-2xl border border-gray-800 text-center relative group hover:bg-zinc-900 transition-colors">
                <div className="w-16 h-16 bg-black border-2 border-green-500 rounded-full flex items-center justify-center mx-auto mb-4 text-green-500 font-bold text-xl shadow-[0_0_15px_rgba(34,197,94,0.3)]">1</div>
                <h3 className="text-xl font-bold text-white mb-2">Sign Up & Share</h3>
                <p className="text-gray-400 text-sm">Apply to become a partner. Once approved, share your unique code to start earning.</p>
            </div>
            <div className="bg-zinc-900/50 p-6 rounded-2xl border border-gray-800 text-center relative group hover:bg-zinc-900 transition-colors">
                <div className="w-16 h-16 bg-black border-2 border-pink-500 rounded-full flex items-center justify-center mx-auto mb-4 text-pink-500 font-bold text-xl shadow-[0_0_15px_rgba(236,72,153,0.3)]">2</div>
                <h3 className="text-xl font-bold text-white mb-2">Recruit & Earn</h3>
                <p className="text-gray-400 text-sm">Invite others to join your team. You earn a <strong>1% commission</strong> on their sales forever!</p>
            </div>
            <div className="bg-zinc-900/50 p-6 rounded-2xl border border-gray-800 text-center relative group hover:bg-zinc-900 transition-colors">
                <div className="w-16 h-16 bg-black border-2 border-purple-500 rounded-full flex items-center justify-center mx-auto mb-4 text-purple-500 font-bold text-xl shadow-[0_0_15px_rgba(168,85,247,0.3)]">3</div>
                <h3 className="text-xl font-bold text-white mb-2">Get Paid</h3>
                <p className="text-gray-400 text-sm">
                    {currency === 'ZAR'
                        ? 'We payout commissions monthly via EFT to your South African bank account.'
                        : 'We pay you monthly in USD via PayPal. Fast and secure.'
                    }
                </p>
            </div>
        </div>

        {/* EARNING POTENTIAL */}
        <div className="space-y-8">
            <div className="text-center">
                <h2 className="text-3xl font-bold text-white mb-4">Earning Potential</h2>
                <p className="text-gray-400 max-w-2xl mx-auto">See what successful partners are earning with our tiered commission structure.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-zinc-900 p-6 rounded-2xl border border-gray-800">
                    <div className="flex items-center gap-3 mb-4">
                        <div className="p-3 bg-green-900/20 rounded-lg text-green-400">
                            <DollarSign size={24} />
                        </div>
                        <div>
                            <h3 className="text-lg font-bold text-white">Passive Income</h3>
                            <p className="text-sm text-gray-400">Recruit 10 Deluxe Members</p>
                        </div>
                    </div>
                    <div className="text-2xl font-bold text-green-400 mb-2">
                        {currency === 'ZAR' ? 'R150/month' : '$30/month'}
                    </div>
                    <p className="text-xs text-gray-500">Earn recurring commissions on their monthly subscriptions forever.</p>
                </div>
                <div className="bg-zinc-900 p-6 rounded-2xl border border-gray-800">
                    <div className="flex items-center gap-3 mb-4">
                        <div className="p-3 bg-yellow-900/20 rounded-lg text-yellow-400">
                            <Trophy size={24} />
                        </div>
                        <div>
                            <h3 className="text-lg font-bold text-white">Weekly Bonus</h3>
                            <p className="text-sm text-gray-400">Hit the milestone</p>
                        </div>
                    </div>
                    <div className="text-2xl font-bold text-yellow-400 mb-2">
                        {currency === 'ZAR' ? 'R200 Cash' : '$15 Cash'}
                    </div>
                    <p className="text-xs text-gray-500">Weekly cash bonuses for reaching sales targets.</p>
                </div>
            </div>
        </div>

        {/* TESTIMONIALS */}
        <div className="space-y-8">
            <div className="text-center">
                <h2 className="text-3xl font-bold text-white mb-4">Partner Success Stories</h2>
                <p className="text-gray-400 max-w-2xl mx-auto">Real partners sharing their experiences with the Spoil Me program.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-zinc-900 p-6 rounded-2xl border border-gray-800">
                    <div className="flex items-center gap-3 mb-4">
                        <div className="w-12 h-12 bg-pink-900/20 rounded-full flex items-center justify-center text-pink-400 font-bold">
                            L
                        </div>
                        <div>
                            <h4 className="font-bold text-white">Lerato, Johannesburg</h4>
                            <p className="text-sm text-gray-400">Started 6 months ago</p>
                        </div>
                    </div>
                    <p className="text-gray-300 text-sm leading-relaxed">
                        "I shared my link on WhatsApp status. My first month I made R2,000 extra cash. The EFT was on time and easy to receive."
                    </p>
                </div>
                <div className={`bg-zinc-900 p-6 rounded-2xl border border-gray-800 ${currency === 'USD' ? 'block' : 'hidden'}`}>
                    <div className="flex items-center gap-3 mb-4">
                        <div className="w-12 h-12 bg-cyan-900/20 rounded-full flex items-center justify-center text-cyan-400 font-bold">
                            J
                        </div>
                        <div>
                            <h4 className="font-bold text-white">Jessica, Texas</h4>
                            <p className="text-sm text-gray-400">Active partner</p>
                        </div>
                    </div>
                    <p className="text-gray-300 text-sm leading-relaxed">
                        "The recurring commission covers my own jewelry addiction! I love getting paid in USD via PayPal."
                    </p>
                </div>
            </div>
        </div>

        {/* DASHBOARD VIEW - Only if Approved */}
        {isAffiliate && (
            <div id="affiliate-dashboard" className="space-y-8 animate-in slide-in-from-bottom-10 duration-700 pt-8 border-t border-gray-800">
                <div className="flex flex-col md:flex-row justify-between items-end gap-4">
                    <div>
                        <h2 className="text-3xl font-bold text-white mb-2">Your Partnership Dashboard</h2>
                        <p className="text-gray-400">Welcome back, {user && user.name ? user.name.split(' ')[0] : 'Partner'}! Manage your links and earnings.</p>
                    </div>
                    <div className="flex gap-2">
                       <Link to="/affiliate/store-builder" className="px-4 py-2 bg-pink-600 hover:bg-pink-500 text-white rounded-lg text-sm font-bold flex items-center gap-2">
                          <Target size={16} /> Build Store
                       </Link>
                       <button onClick={handleBuyContent} className="px-4 py-2 bg-zinc-800 hover:bg-zinc-700 text-white rounded-lg text-sm border border-gray-700 flex items-center gap-2">
                          <FileText size={16} /> Content Assets
                       </button>
                       {!stats.isElite && (
                           <button onClick={handleJoinElite} className="px-4 py-2 bg-gradient-to-r from-yellow-600 to-orange-600 text-white rounded-lg text-sm font-bold flex items-center gap-2 hover:brightness-110">
                              <Crown size={16} /> Go Elite
                           </button>
                       )}
                    </div>
                </div>

                {/* Stats Cards */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="bg-zinc-900 p-6 rounded-2xl border border-gray-800">
                        <div className="flex justify-between items-start mb-4">
                            <div className="p-3 bg-green-900/20 rounded-lg text-green-400">
                                <DollarSign size={24} />
                            </div>
                            <span className="text-xs bg-zinc-800 px-2 py-1 rounded text-gray-400">Total Earnings</span>
                        </div>
                        <div className="text-3xl font-bold text-white">R{stats.balance.toFixed(2)}</div>
                        <div className="text-xs text-gray-500 mt-1">Next payout date: 1st of month</div>
                    </div>

                    <div className="bg-zinc-900 p-6 rounded-2xl border border-gray-800">
                        <div className="flex justify-between items-start mb-4">
                            <div className="p-3 bg-blue-900/20 rounded-lg text-blue-400">
                                <Users size={24} />
                            </div>
                            <span className="text-xs bg-zinc-800 px-2 py-1 rounded text-gray-400">Direct Sales</span>
                        </div>
                        <div className="text-3xl font-bold text-white">{stats.totalSalesCount}</div>
                        <div className="text-xs text-gray-500 mt-1">Value: R{stats.totalSalesValue.toFixed(0)}</div>
                    </div>

                    <div className="bg-zinc-900 p-6 rounded-2xl border border-gray-800">
                        <div className="flex justify-between items-start mb-4">
                            <div className="p-3 bg-purple-900/20 rounded-lg text-purple-400">
                                <Star size={24} />
                            </div>
                            <span className="text-xs bg-zinc-800 px-2 py-1 rounded text-gray-400">Current Rate</span>
                        </div>
                        <div className="text-3xl font-bold text-white">{stats.commissionRate}%</div>
                        <div className="text-xs text-purple-400 mt-1">Tier: {currentTier.name}</div>
                    </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                    {/* Link Generator */}
                    <div className="bg-zinc-900 p-6 rounded-2xl border border-gray-800">
                        <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                            <Share2 size={20} className="text-pink-500" /> Your Referral Link
                        </h3>
                        <div className="bg-black p-4 rounded-xl border border-gray-700 flex flex-col gap-3">
                            <div className="flex flex-col md:flex-row gap-4 items-center">
                                <code className="flex-1 text-cyan-400 text-sm break-all font-mono bg-zinc-900/50 p-3 rounded border border-gray-800 w-full">
                                    {window.location.origin}/#/?ref={user.affiliateCode}
                                </code>
                                <button 
                                    onClick={copyLink}
                                    className="w-full md:w-auto px-6 py-3 bg-zinc-800 hover:bg-zinc-700 text-white text-xs font-bold rounded-lg transition-colors flex items-center justify-center gap-2 border border-gray-600"
                                >
                                    {copiedLink ? <Check size={14} /> : <Copy size={14} />}
                                    {copiedLink ? "Copied!" : "Copy Link"}
                                </button>
                            </div>
                        </div>
                        <div className="mt-4 bg-pink-900/20 p-3 rounded-lg border border-pink-500/20">
                            <p className="text-xs text-pink-300">
                                <strong>Tip:</strong> Customers get <strong>5% OFF</strong> when using your code <code>{user.affiliateCode}</code> at checkout!
                            </p>
                        </div>
                    </div>

                    {/* Recruitment Center (NEW) */}
                    <div className="bg-gradient-to-br from-zinc-900 to-black p-6 rounded-2xl border border-cyan-500/30 relative overflow-hidden">
                        <div className="absolute top-0 right-0 p-4 opacity-10 pointer-events-none">
                            <Network size={80} className="text-cyan-500" />
                        </div>
                        <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2 relative z-10">
                            <Users size={20} className="text-cyan-400" /> Recruitment Center
                        </h3>
                        
                        <div className="bg-cyan-900/20 border border-cyan-500/30 p-4 rounded-xl mb-6 relative z-10">
                            <div className="flex items-start gap-3">
                                <div className="p-2 bg-cyan-500/20 rounded-full text-cyan-400 shrink-0">
                                    <DollarSign size={16} />
                                </div>
                                <div>
                                    <h4 className="text-sm font-bold text-white">Earn 1% Override Commission</h4>
                                    <p className="text-xs text-gray-400 mt-1">
                                        Recruit new affiliates and earn 1% of their sales volume forever. No impact on their earnings!
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div className="space-y-3 relative z-10">
                            <h4 className="text-xs text-gray-500 uppercase font-bold tracking-wider">My Recruits ({myRecruits.length})</h4>
                            {myRecruits.length > 0 ? (
                                <div className="max-h-[150px] overflow-y-auto pr-2 space-y-2 custom-scrollbar">
                                    {myRecruits.map(recruit => (
                                        <div key={recruit.id} className="flex justify-between items-center p-2 bg-black/40 rounded border border-gray-800">
                                            <div className="flex items-center gap-2">
                                                <div className="w-6 h-6 bg-zinc-800 rounded-full flex items-center justify-center text-[10px] text-gray-400 border border-gray-700">
                                                    {recruit.name ? recruit.name.charAt(0) : '?'}
                                                </div>
                                                <span className="text-xs text-gray-300">{recruit.name}</span>
                                            </div>
                                            <span className="text-xs text-green-400 font-mono">
                                                Sales: R{recruit.affiliateStats?.totalSalesValue.toFixed(0)}
                                            </span>
                                        </div>
                                    ))}
                                </div>
                            ) : (
                                <div className="text-center py-4 border border-dashed border-gray-800 rounded-lg">
                                    <p className="text-xs text-gray-500">No recruits yet. Start building your team!</p>
                                </div>
                            )}
                        </div>
                        
                        <div className="mt-4 pt-4 border-t border-gray-800 relative z-10">
                            <p className="text-[10px] text-gray-500 mb-2">Share your recruitment link:</p>
                            <div className="flex items-center gap-2">
                                <code className="flex-1 bg-black p-2 rounded text-[10px] text-gray-400 truncate border border-gray-800">
                                    {window.location.origin}/#/?ref={user.affiliateCode}
                                </code>
                                <button onClick={copyLink} className="text-xs text-cyan-400 hover:text-cyan-300 font-bold">
                                    Copy
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        )}

        {/* COMMISSION TIERS */}
        <div className="space-y-8">
            <div className="text-center">
                <h2 className="text-3xl font-bold text-white mb-4">Commission Tiers</h2>
                <p className="text-gray-400 max-w-2xl mx-auto">Your commission rate increases based on your all-time sales performance.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                {tiers.map((tier, index) => (
                    <div key={tier.name} className={`p-6 rounded-2xl border transition-all ${currentTier.name === tier.name ? 'bg-gradient-to-br from-yellow-900/20 to-orange-900/20 border-yellow-500/50 shadow-[0_0_20px_rgba(234,179,8,0.2)]' : 'bg-zinc-900 border-gray-800'}`}>
                        <div className="text-center">
                            <div className={`inline-flex items-center justify-center w-12 h-12 rounded-full mb-3 ${currentTier.name === tier.name ? 'bg-yellow-500 text-black' : 'bg-zinc-800 text-gray-400'}`}>
                                <Award size={20} />
                            </div>
                            <h3 className={`text-lg font-bold mb-1 ${currentTier.name === tier.name ? 'text-yellow-400' : 'text-white'}`}>{tier.name}</h3>
                            <div className={`text-2xl font-bold mb-2 ${currentTier.name === tier.name ? 'text-yellow-400' : 'text-gray-300'}`}>{tier.rate}%</div>
                            <p className="text-xs text-gray-500">
                                {currency === 'ZAR'
                                    ? `R${tier.min.toLocaleString()} - ${tier.max === Infinity ? '∞' : 'R' + tier.max.toLocaleString()}`
                                    : `$${tier.min.toLocaleString()} - ${tier.max === Infinity ? '∞' : '$' + tier.max.toLocaleString()}`
                                }
                            </p>
                        </div>
                    </div>
                ))}
            </div>
        </div>

        {/* TERMS MODAL OVERLAY */}
        {showTermsModal && (
            <div className="fixed inset-0 z-[60] flex items-center justify-center px-4">
                <div className="absolute inset-0 bg-black/95 backdrop-blur-xl" onClick={() => !allTermsChecked && setShowTermsModal(false)} />
                <div className="bg-zinc-900 border border-gray-700 rounded-2xl p-6 max-w-3xl w-full relative z-20 shadow-2xl h-[90vh] flex flex-col animate-in zoom-in-95 duration-200">
                    <div className="flex justify-between items-center mb-4 pb-4 border-b border-gray-800">
                        <h3 className="text-xl font-bold text-white flex items-center gap-2">
                            <BookOpen size={20} className="text-pink-500" /> Terms & Conditions
                        </h3>
                        <button onClick={() => setShowTermsModal(false)} className="text-gray-500 hover:text-white">
                            <X size={20} />
                        </button>
                    </div>
                    
                    <div className="flex-1 overflow-y-auto custom-scrollbar space-y-8 pr-4">
                        <div className="bg-yellow-900/10 border border-yellow-500/20 p-4 rounded-lg mb-6 text-yellow-200 text-sm">
                            Please read each section carefully. You must acknowledge each section to proceed.
                        </div>

                        {termsSections.map((section, index) => (
                            <div key={index} className="bg-black/30 rounded-xl p-5 border border-gray-800 hover:border-gray-700 transition-colors">
                                <h4 className="text-lg font-bold text-white mb-3">{section.title}</h4>
                                <div className="text-sm text-gray-400 leading-relaxed whitespace-pre-wrap font-sans mb-4 pl-2 border-l-2 border-gray-700">
                                    {section.content}
                                </div>
                                <label className={`flex items-center gap-3 cursor-pointer p-3 rounded-lg transition-all ${sectionAgreements[index] ? 'bg-green-900/20 border border-green-500/30' : 'bg-zinc-800/50 border border-gray-700 hover:bg-zinc-800'}`}>
                                    <div className={`w-5 h-5 rounded flex items-center justify-center border ${sectionAgreements[index] ? 'bg-green-500 border-green-500 text-black' : 'bg-black border-gray-600 text-transparent'}`}>
                                        <Check size={14} strokeWidth={4} />
                                    </div>
                                    <input 
                                        type="checkbox" 
                                        className="hidden" 
                                        checked={!!sectionAgreements[index]}
                                        onChange={() => toggleSectionAgreement(index)}
                                    />
                                    <span className={`text-sm font-bold ${sectionAgreements[index] ? 'text-green-400' : 'text-gray-400'}`}>
                                        I have read and agree to the {section.title}
                                    </span>
                                </label>
                            </div>
                        ))}
                    </div>

                    <div className="mt-4 pt-4 border-t border-gray-800 flex justify-between items-center">
                        <div className="text-xs text-gray-500">
                            {Object.values(sectionAgreements).filter(Boolean).length} of {termsSections.length} sections agreed
                        </div>
                        <button 
                            onClick={handleConfirmTerms}
                            disabled={!allTermsChecked}
                            className="px-8 py-3 bg-pink-600 hover:bg-pink-500 text-white font-bold rounded-xl transition-all disabled:opacity-30 disabled:cursor-not-allowed flex items-center gap-2 shadow-lg"
                        >
                            {allTermsChecked ? <Check size={18} /> : <Lock size={18} />}
                            {allTermsChecked ? 'Confirm Agreement' : 'Agree to All Sections to Continue'}
                        </button>
                    </div>
                </div>
            </div>
        )}

        {/* PENDING STATUS POPUP */}
        {showPendingModal && (
            <div className="fixed inset-0 z-[70] flex items-center justify-center px-4">
                <div className="absolute inset-0 bg-black/90 backdrop-blur-sm" onClick={() => setShowPendingModal(false)} />
                <div className="bg-zinc-900 border border-yellow-500/50 rounded-2xl p-8 max-w-md w-full relative z-20 shadow-[0_0_50px_rgba(234,179,8,0.2)] animate-in zoom-in-95 duration-200 text-center">
                    <div className="w-20 h-20 bg-yellow-900/20 border-2 border-yellow-500 rounded-full flex items-center justify-center mx-auto mb-6 animate-pulse">
                        <Clock size={40} className="text-yellow-500" />
                    </div>
                    <h2 className="text-2xl font-bold text-white mb-2">Application Under Review</h2>
                    <p className="text-gray-300 text-sm leading-relaxed mb-6">
                        Thank you for applying to the Spoil Me Vintage Partnership Program. <br/><br/>
                        Our team is currently reviewing your application details. This process typically takes <strong>24-48 hours</strong>.
                    </p>
                    <button 
                        onClick={() => setShowPendingModal(false)}
                        className="w-full py-3 bg-yellow-600 hover:bg-yellow-500 text-black font-bold rounded-xl transition-colors"
                    >
                        Understood
                    </button>
                </div>
            </div>
        )}

        {/* APPLICATION FORM MODAL */}
        {showApplyForm && (
            <div className="fixed inset-0 z-50 flex items-center justify-center px-4">
                <div className="absolute inset-0 bg-black/90 backdrop-blur-md" onClick={closeAndReset} />
                <div className="bg-zinc-900 border border-pink-500 rounded-2xl p-8 max-w-xl w-full relative z-10 shadow-2xl animate-in zoom-in-95 duration-200 max-h-[95vh] overflow-y-auto">
                    
                    {applicationSubmitted ? (
                        <div className="text-center py-8 px-4">
                            <div className="bg-zinc-800 border border-green-500/30 rounded-2xl p-8 shadow-[0_0_40px_rgba(34,197,94,0.1)] relative overflow-hidden">
                                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-green-500 to-cyan-500"></div>
                                <div className="w-20 h-20 bg-black border-2 border-green-500 rounded-full flex items-center justify-center mx-auto shadow-[0_0_20px_rgba(34,197,94,0.4)] mb-6">
                                    <Check size={40} className="text-green-500" />
                                </div>
                                <h2 className="text-2xl font-bold text-white mb-2">Application Received!</h2>
                                <p className="text-gray-300 text-sm leading-relaxed">
                                    Thank you, <strong>{formData.name}</strong>. Your application has been sent to our admin team for review.
                                </p>
                                <button 
                                    onClick={closeAndReset}
                                    className="mt-8 w-full py-3 bg-white text-black font-bold rounded-xl hover:bg-gray-200 transition-colors shadow-lg"
                                >
                                    Done
                                </button>
                            </div>
                        </div>
                    ) : loginMode ? (
                        <div className="space-y-6">
                            <div className="text-center border-b border-gray-800 pb-4">
                                <h2 className="text-2xl font-bold text-white">Welcome Back</h2>
                                <p className="text-sm text-gray-400 mt-1">Please log in to continue your application.</p>
                            </div>
                            
                            {loginError && (
                                <div className="p-3 bg-red-900/20 border border-red-500/50 rounded-lg flex gap-2 items-center text-red-400 text-sm">
                                    <AlertCircle size={16} /> {loginError}
                                </div>
                            )}

                            <form onSubmit={handleInlineLogin} className="space-y-4">
                                <div>
                                    <label className="block text-xs text-gray-500 uppercase mb-1">Email Address</label>
                                    <input 
                                        type="email" 
                                        value={formData.email}
                                        readOnly 
                                        className="w-full bg-zinc-800 border border-gray-700 rounded-lg p-3 text-gray-400 text-sm cursor-not-allowed"
                                    />
                                </div>
                                <div>
                                    <label className="block text-xs text-gray-500 uppercase mb-1">Password</label>
                                    <input 
                                        type="password" 
                                        value={loginPassword}
                                        onChange={(e) => setLoginPassword(e.target.value)}
                                        required
                                        className="w-full bg-black border border-gray-700 rounded-lg p-3 text-white text-sm focus:border-pink-500 outline-none"
                                        placeholder="••••••"
                                    />
                                </div>
                                <button 
                                    type="submit"
                                    className="w-full py-3 bg-cyan-600 hover:bg-cyan-500 text-white font-bold rounded-xl transition-all shadow-lg flex items-center justify-center gap-2"
                                >
                                    <LogIn size={18} /> Login & Continue Application
                                </button>
                            </form>
                            <div className="text-center">
                                <button onClick={() => setLoginMode(false)} className="text-xs text-gray-500 hover:text-white underline">
                                    Go Back
                                </button>
                            </div>
                        </div>
                    ) : (
                        <>
                            <div className="flex justify-between items-center mb-6">
                                <h2 className="text-2xl font-bold text-white">Apply to Partner</h2>
                                <button onClick={closeAndReset} className="text-gray-500 hover:text-white"><X size={24} /></button>
                            </div>

                            {step === 1 && (
                                <div className="space-y-6">
                                    <div className="bg-purple-900/20 border border-purple-500/30 p-4 rounded-xl">
                                        <h3 className="text-purple-400 font-bold mb-2 flex items-center gap-2"><Lock size={18} /> Reality Check</h3>
                                        <p className="text-gray-300 text-sm leading-relaxed">
                                            This is a business partnership. Inactive accounts (0 sales in 3 months) may be deactivated.
                                        </p>
                                    </div>
                                    <label className="flex items-start gap-3 cursor-pointer group">
                                        <div className={`mt-1 w-5 h-5 rounded border flex items-center justify-center ${acknowledgeReality ? 'bg-pink-500 border-pink-500' : 'border-gray-600'}`}>
                                            {acknowledgeReality && <Check size={14} className="text-white" />}
                                        </div>
                                        <input type="checkbox" className="hidden" checked={acknowledgeReality} onChange={e => setAcknowledgeReality(e.target.checked)} />
                                        <span className="text-sm text-gray-400 group-hover:text-white transition-colors">
                                            I understand that this program requires active participation.
                                        </span>
                                    </label>
                                    <button 
                                        disabled={!acknowledgeReality}
                                        onClick={() => setStep(2)}
                                        className="w-full py-3 bg-pink-600 hover:bg-pink-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold rounded-xl transition-all"
                                    >
                                        Continue
                                    </button>
                                </div>
                            )}

                            {step === 2 && (
                                <form onSubmit={handleApply} className="space-y-4">
                                    {!user.email && (
                                        <div className="p-3 bg-zinc-800 rounded-lg border border-gray-700 mb-4">
                                            <p className="text-xs text-gray-400 mb-2">Create your account to get started:</p>
                                            <div className="grid grid-cols-2 gap-3 mb-3">
                                                <input type="text" placeholder="First Name" required className="bg-black border border-gray-700 rounded p-2 text-white text-sm" value={formData.name} onChange={e => setFormData({...formData, name: e.target.value})} />
                                                <input type="text" placeholder="Surname" required className="bg-black border border-gray-700 rounded p-2 text-white text-sm" value={formData.surname} onChange={e => setFormData({...formData, surname: e.target.value})} />
                                            </div>
                                            <div className="space-y-3">
                                                <input type="email" placeholder="Email Address" required className="w-full bg-black border border-gray-700 rounded p-2 text-white text-sm" value={formData.email} onChange={e => setFormData({...formData, email: e.target.value})} />
                                                <input type="password" placeholder="Create Password" required className="w-full bg-black border border-gray-700 rounded p-2 text-white text-sm" value={formData.password} onChange={e => setFormData({...formData, password: e.target.value})} />
                                                <div className="grid grid-cols-2 gap-3">
                                                    <input type="date" required className="bg-black border border-gray-700 rounded p-2 text-white text-sm" value={formData.dob} onChange={e => setFormData({...formData, dob: e.target.value})} />
                                                    <select className="bg-black border border-gray-700 rounded p-2 text-white text-sm" required value={formData.gender} onChange={e => setFormData({...formData, gender: e.target.value})}>
                                                        <option value="">Gender</option>
                                                        <option value="Male">Male</option>
                                                        <option value="Female">Female</option>
                                                        <option value="Other">Other</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    )}

                                    <div>
                                        <label className="block text-xs text-gray-500 uppercase mb-1">Why do you want to join?</label>
                                        <textarea 
                                            required 
                                            className="w-full bg-black border border-gray-700 rounded-lg p-3 text-white text-sm focus:border-pink-500 outline-none h-24"
                                            placeholder="Tell us about your audience or marketing plan..."
                                            value={formData.reason}
                                            onChange={e => setFormData({...formData, reason: e.target.value})}
                                        />
                                    </div>
                                    <div>
                                        <label className="block text-xs text-gray-500 uppercase mb-1">Social Media Links</label>
                                        <input 
                                            type="text" 
                                            className="w-full bg-black border border-gray-700 rounded-lg p-3 text-white text-sm focus:border-pink-500 outline-none"
                                            placeholder="Instagram, TikTok, Blog URL..."
                                            value={formData.socials}
                                            onChange={e => setFormData({...formData, socials: e.target.value})}
                                        />
                                    </div>

                                    {/* PAYMENT DETAILS - Currency Specific */}
                                    {currency === 'ZAR' ? (
                                        <div className="space-y-3">
                                            <h4 className="text-sm font-bold text-white">Banking Details (EFT Payments)</h4>
                                            <div className="grid grid-cols-2 gap-3">
                                                <input type="text" placeholder="Bank Name" required className="bg-black border border-gray-700 rounded p-2 text-white text-sm" />
                                                <input type="text" placeholder="Account Number" required className="bg-black border border-gray-700 rounded p-2 text-white text-sm" />
                                            </div>
                                            <input type="text" placeholder="Branch Code" required className="w-full bg-black border border-gray-700 rounded p-2 text-white text-sm" />
                                        </div>
                                    ) : (
                                        <div className="space-y-3">
                                            <h4 className="text-sm font-bold text-white">PayPal Details (USD Payments)</h4>
                                            <input type="email" placeholder="PayPal Email Address" required className="w-full bg-black border border-gray-700 rounded p-2 text-white text-sm" />
                                        </div>
                                    )}

                                    <div className="pt-2">
                                        <button 
                                            type="button"
                                            onClick={() => setShowTermsModal(true)}
                                            className={`w-full flex items-center justify-between p-4 rounded-xl border transition-all ${acceptTerms ? 'bg-green-900/20 border-green-500 text-green-400' : 'bg-zinc-800 border-gray-700 text-gray-300 hover:border-gray-500'}`}
                                        >
                                            <span className="text-sm font-bold flex items-center gap-2">
                                                <BookOpen size={16} /> {acceptTerms ? 'Terms Accepted' : 'Read Terms & Conditions'}
                                            </span>
                                            {acceptTerms ? <CheckCircle size={18} /> : <ArrowRight size={16} />}
                                        </button>
                                        {!acceptTerms && <p className="text-xs text-red-400 mt-1 text-center">You must accept terms to proceed.</p>}
                                    </div>

                                    <button 
                                        type="submit"
                                        disabled={!acceptTerms}
                                        className="w-full py-4 bg-pink-600 hover:bg-pink-500 disabled:opacity-50 disabled:cursor-not-allowed text-white font-bold rounded-xl shadow-[0_0_20px_rgba(236,72,153,0.4)] transition-all mt-4"
                                    >
                                        Submit Application
                                    </button>
                                </form>
                            )}
                        </>
                    )}
                </div>
            </div>
        )}

        {/* CURRENCY SELECTION MODAL */}
        <CurrencySelectionModal
            isOpen={showCurrencyModal}
            onClose={() => setShowCurrencyModal(false)}
        />
    </div>
  );
};

export default AffiliateProgram;
